# === Makefile.linux ===

CC = gcc
WARNINGS = -Werror
CFLAGS = -O0 -mavx2 -std=gnu17 $(WARNINGS)
INCLUDES = -Isrc
LDFLAGS = -lm -lX11 -lpng -ljpeg
SRC_DIR = src
BUILD_DIR = build
LIB_DIR = libs
BIN_DIR = bin
TARGET = $(BUILD_DIR)/Main

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))

LIB_FILES = $(wildcard $(LIB_DIR)/*.c)
SO_FILES = $(patsubst $(LIB_DIR)/%.c,$(BIN_DIR)/%.so,$(LIB_FILES))

all: $(BUILD_DIR) $(TARGET)

alldebug:
	$(CC) -g $(CFLAGS) $(INCLUDES) ./$(SRC_DIR)/Main.c -o ./$(TARGET) $(LDFLAGS) 

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) $(INCLUDES) $(SRCS) -o $(TARGET) $(LDFLAGS)

debug:
	gdb ./$(TARGET)

exe:
	./$(TARGET)

clean:
	rm -rf $(BUILD_DIR)/*

cleanlib:
	rm -rf $(BIN_DIR)/*

lib: $(SO_FILES)

$(BIN_DIR)/%.so: $(LIB_DIR)/%.c
	$(CC) $(CFLAGS) -fPIC -o $@ $< -shared $(LDFLAGS)

do: clean all exe

dg: clean alldebug debug

# === Makefile.linux ===